name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3

      - name: Heroku Build
        uses: behe/heroku-build@v1.1
        with:
          # Name of Heroku application
          app-name: wj9studios
          # API key with the deploy role
          api-key: ${{ secrets.HEROKU_TOKEN }}
          # Directory to upload
          path: .
